namespace: argocd
resources:
  - ../../base/cert-manager-ns.yaml
  - base/cert-manager-app.yaml
  # - ../../base/ingress-nginx-ns.yaml
  # - ../../base/ingress-nginx-app.yaml
  - ../../base/prometheus-operator-ns.yaml
  - ../../base/prometheus-operator-app.yaml
