apiVersion: v1
kind: Secret
metadata:
    name: argocd-repositories-secret
    labels:
        app.kubernetes.io/name: argocd-repositories-secret
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CRvfhcdpKw==,iv:oBl6TKVx6oc49qY089qSP0jg8HomJadZ3stcLJgZ7B8=,tag:FhuiLOT5CTNSajLW8f0hMQ==,type:str]
    password: ENC[AES256_GCM,data:pg1p76NJVE+/2iw6FC8gBT73W2An6zNBhVD+4oNMd37CPhNOWqlkTg==,iv:HGTkmLFzDP1tm1nlQ5V9B+UObx50U6AWgEvfbO4Wl4Y=,tag:e3+Dm8NGwNbRhaHH7ANqDA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/dev-host-environment-4d3e/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-02-24T16:52:29Z'
        enc: CiQAwFdWAT8L0V23jLm7KPUAnibGZMlg/mSh1iw9e5YswtoSJV0SSQAlA7NyIn+s1jgpPQSS37uVvYfPUO7jDnGRRCifZF5+AVRK+IkIqvNJeR7feDZZq8+8MRetmGbnMLZNJuXUil3hoIFttdWhiPE=
    azure_kv: []
    lastmodified: '2020-02-24T16:52:29Z'
    mac: ENC[AES256_GCM,data:v3w9OjSBSyfFri7eC/lF08gsiMK/0bzsOfW70uCf1fgaT0mJH+aY32B3Us7roNaoI7JPS23JDPhdi+ZdHx2LaPxSFBTeL2r0RQCFOgJ6yzmKujQGwawhMRk9s4FAn+EWbgQVO6fFGc6WqujlD2Z92eesr0Xf0fzr8pZJGH9noC0=,iv:h9msrHVdbn8ViXIS/UOnlT90MFBACclohFUu8b7LFRY=,tag:szz7WejKRYeLwghJrKSOdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
