apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-provisioner
spec:
  # Source of the application manifests
  source:
    repoURL: https://github.com/pmcjury/argocd-operator-multi-tenant
