apiVersion: v1
kind: Secret
metadata:
    name: argocd-repositories-secret
    labels:
        app.kubernetes.io/name: argocd-repositories-secret
        app.kubernetes.io/part-of: argocd
type: Opaque
data:
    username: ENC[AES256_GCM,data:K9s8WFAahw==,iv:NKXxEXLXo9KGDhmIqgEzRz8+r6KTcH1WjOASpCSgu4I=,tag:mSMmQrwZXhCyNkfzoFuUsg==,type:str]
    password: ENC[AES256_GCM,data:o7VgHygBf9OEivhRyAK5omo+sqw0d+ec46137cdMC8wzTydzGwLgtg==,iv:ZlGk5Xv83wWIsa8ScfonkRGKE1be78SzeVW5XrXyNcg=,tag:LvWGs/Z/PLj3oC8Pz89yVQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dev-host-environment-4d3e/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2020-02-22T20:17:46Z"
          enc: CiQAwFdWAY9/QPO3wAdjpxfEBggpQwfPfV5ZzUJoEPv8sbTwxlkSSQAlA7NytTkWAPM0OzPNeq/Fsu2GgVIZ0uVZc6CHF/DjzY4qyjO86PcLSgYEdvxTCetsOuxib2MO1zMI8lniVT/P5NkcSlMiyYU=
    azure_kv: []
    lastmodified: "2020-02-22T20:17:47Z"
    mac: ENC[AES256_GCM,data:WyNSQCKMMMrAD/3tptRPmTZ39+p9Ef0OPb4QyGKWe3SI5J6gyfLZ2lUuBgwKQuV8Ck1Uddh9tTJGX6otii9f67pKTXG4AGwUIN3exJZQ21yMtPASONV86VocTIOQ5s5ttK/AwFpLTIyjCQWU4uTrhM2bdn8eJ/5RJzOufJN18HE=,iv:YkFpxsjCKEWhF4UmqKG+CzL6CJSZTXmkeh0XQhzwXiY=,tag:bPPinw1/oEApxJWPV3LU7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
