apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: ingress
spec:
  ingress:
    enabled: true
  server:
    insecure: true
    host: argocd.test
    grpc:
      host: argocd-grpc.test
